runtime: python
env: flex
entrypoint: python -m bot
runtime_config :
    operating_system: "ubuntu18"
    runtime : 3.10.9
env_variables :
    'TOKEN': "6161267898:AAFu3abUnJczMVqqK4iwBimKjESqtXzG3xM"